#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "bentopdf"
name = "BentoPDF"
description.en = "Privacy First PDF Toolkit"
description.fr = "Kit d'outils PDF Privacy First"

version = "2.2.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://bentopdf.com"
admindoc = "https://bentopdf.com/docs/self-hosting/"
code = "https://github.com/alam00000/bentopdf"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "2000M"
ram.build = "3000M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/bentopdf"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/alam00000/bentopdf/archive/refs/tags/v2.2.0.tar.gz"
    sha256 = "c038020657bd32d2a45a1edc4603dc0643d10b335e8f457c043341e183429f36"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"

    [resources.nodejs]
    version = "22"
